### ISSUE TITLE
Move to jupyter-widgets

### ISSUE THREAD

**Issue by jasongrout** [jupyter-widgets/opinionated-widget-cookiecutter#4]
How do you feel about moving this to the jupyter-widgets org to be the official cookie cutter?

**Comment by vidartf** [comment]
I probably want to keep my own copy, but if that means to transfer to jupyter and then fork back, I'm happy with that. That being said, I'd argue for also keeping a minimal cookiecutter in pure JS, with minimal tooling. It is a good learning resource, and is handy for those who want to integrate widget development into their own tooling setup.

**Comment by vidartf** [comment]
Transferred. Feel free to rename / update readme as appropriate.

**Comment by jasongrout** [comment]
Thanks! I agree about also keeping a minimal js cookie cutter.

**Comment by jasongrout** [comment]
@vidartf - Is it all right with you if we apply the standard Project Jupyter licensing and copyright statements to the files in this repo, at least the ones that make sense? (I don't think applying a license to the templates makes sense...)

**Comment by vidartf** [comment]
Oh yeah, I didn't realize the root repo was missing a license. Standard BSD-3 etc. should be OK.
